service: visa-rescheduler-lambda

provider:
  name: aws
  logRetentionInDays: 5
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 'events:PutRule'
          Resource: "arn:aws:events:*:*:rule/visa-rescheduler-lambda*"


  stage: ${opt:stage, 'prod'}
  region: ${env:AWS_REGION, 'us-east-1'}
  ecr:
    images:
      img:
        path: ./
        platform: linux/amd64

functions:
  main:
    timeout: 60
    # If you experience any errors such as Chrome crashing or not being available you might need to increase the storage available to your Lambda Function.
    memorySize: 2048
    image:
      name: img
    events:
      - eventBridge:
          schedule: rate(${file(./json_var.json):retry_value, '10'} minutes)